name: 2 - Scrape Protocols

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: [self-hosted]
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0"

      - name: Run scraper
        working-directory: src/scraper
        env:
          STORAGE_ACCOUNT_URL: https://<your-storage-account>.blob.core.windows.net/
          AZURE_CONTAINER_NAME: protocols
        run: dotnet run --configuration Release
